<?php
/**
 * InlineResponse200ResultsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  GoogleApi\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Google GeoCode API
 *
 * API for handling of the geocode
 *
 * OpenAPI spec version: 1.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.15-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace GoogleApi\Client;

/**
 * InlineResponse200ResultsTest Class Doc Comment
 *
 * @category    Class
 * @description InlineResponse200Results
 * @package     GoogleApi\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse200ResultsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InlineResponse200Results"
     */
    public function testInlineResponse200Results()
    {
    }

    /**
     * Test attribute "addressComponents"
     */
    public function testPropertyAddressComponents()
    {
    }

    /**
     * Test attribute "formattedAddress"
     */
    public function testPropertyFormattedAddress()
    {
    }

    /**
     * Test attribute "geometry"
     */
    public function testPropertyGeometry()
    {
    }

    /**
     * Test attribute "placeId"
     */
    public function testPropertyPlaceId()
    {
    }

    /**
     * Test attribute "plusCode"
     */
    public function testPropertyPlusCode()
    {
    }

    /**
     * Test attribute "types"
     */
    public function testPropertyTypes()
    {
    }
}
