<?php
/**
 * GeocodeApiTest
 * PHP version 5
 *
 * @category Class
 * @package  GoogleApi\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Google GeoCode API
 *
 * API for handling of the geocode
 *
 * OpenAPI spec version: 1.0.5
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.15-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace GoogleApi\Client;

use \GoogleApi\Client\Configuration;
use \GoogleApi\Client\ApiException;
use \GoogleApi\Client\ObjectSerializer;

/**
 * GeocodeApiTest Class Doc Comment
 *
 * @category Class
 * @package  GoogleApi\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class GeocodeApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getInformation
     *
     * Gets Geo-Information about the specified place.
     *
     */
    public function testGetInformation()
    {
    }
}
